name: GitHubPagesのためのフロントエンドビルド

on:
  push:
    branches:
      - main

jobs:
  frontend_build:
    name: frontend build for github pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cache node_modules
        id: cache_node
        uses: actions/cache@v3
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        if: steps.cache_node.outputs.cache-hit != 'true'
        run: cd frontend && yarn install

      - name: build
        run: cd frontend && yarn build

      - name: export
        run: cd frontend && yarn export

      # GitHubPagesの_ディレクトリ読めない仕様回避
      - name: add nojekyll
        run: cd frontend && touch ./out/.nojekyll

      # GitHubPagesがCNAMEをgh-pagesブランチに作ってしまい、毎回消えるので、mainブランチで保持してコピーする
      - name: copy CNAME
        run: cp CNAME ./frontend/out

      # 公開用のリポジトリにプッシュ
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.USUYUKI_GITHUB_TOKEN }}
          publish_dir: ./frontend/out
